name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build with Vite
      run: npm run build

    - name: Build Electron
      run: npm run build:electron
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: matrix.node-version == '20.x'
      with:
        name: build-artifacts
        path: |
          dist/
          electron-dist/
        retention-days: 7

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Validate Docker configuration
      run: |
        chmod +x test-docker-setup.sh
        ./test-docker-setup.sh

    - name: Build Docker image
      run: docker build -t ai-agent-browser:test .

    - name: Test Docker Compose
      run: |
        docker compose config --quiet
        echo "✅ Docker Compose configuration is valid"
